# Generated by Django 5.2.10 on 2026-01-14 05:38

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='contact_no',
            field=models.CharField(default='9999999999', max_length=10, validators=[app.models.validate_contact_number]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
