# Generated by Django 5.2.10 on 2026-01-15 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_student_contact_no_alter_student_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='marksheet_10',
            field=models.FileField(blank=True, null=True, upload_to='marksheets/'),
        ),
        migrations.AddField(
            model_name='student',
            name='marksheet_12',
            field=models.FileField(blank=True, null=True, upload_to='marksheets/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
