# Generated by Django 5.2.10 on 2026-01-15 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_student_marksheet_10_student_marksheet_12_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='marksheet_10',
        ),
        migrations.RemoveField(
            model_name='student',
            name='marksheet_12',
        ),
    ]
