# Generated by Django 5.2.10 on 2026-01-15 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_student_marksheet_10_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marksheet_10', models.FileField(blank=True, null=True, upload_to='marksheets/10th/')),
                ('marksheet_12', models.FileField(blank=True, null=True, upload_to='marksheets/12th/')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='app.student')),
            ],
        ),
    ]
