# Generated by Django 5.2.10 on 2026-01-18 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auditlog_description_alter_auditlog_action'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auditlog',
            old_name='timestamp',
            new_name='created_at',
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(max_length=100),
        ),
    ]
